export {};

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */
export type Booking = {
  _id: string;
  _type: "booking";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "userProfile";
  };
  classSession?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "classSession";
  };
  status?: "confirmed" | "cancelled" | "attended" | "noShow";
  createdAt?: string;
  cancelledAt?: string;
  attendedAt?: string;
};

export type ClassSession = {
  _id: string;
  _type: "classSession";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  activity?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "activity";
  };
  venue?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "venue";
  };
  startTime?: string;
  maxCapacity?: number;
  status?: "scheduled" | "cancelled" | "completed";
};

export type Activity = {
  _id: string;
  _type: "activity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  instructor?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  duration?: number;
  tierLevel?: "basic" | "performance" | "champion";
  aiKeywords?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  address?: {
    fullAddress?: string;
    street?: string;
    city?: string;
    postcode?: string;
    country?: string;
    lat?: number;
    lng?: number;
  };
  amenities?: Array<string>;
  openingHours?: Array<{
    day?: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    open?: string;
    close?: string;
    _key: string;
  }>;
};

export type UserProfile = {
  _id: string;
  _type: "userProfile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  imageUrl?: string;
  subscriptionTier?: "none" | "basic" | "performance" | "champion";
  location?: {
    lat?: number;
    lng?: number;
    address?: string;
  };
  searchRadius?: 5 | 10 | 25 | 50;
  createdAt?: string;
};

// ✅ Explicit exports for app usage
 export type {
  USER_BOOKINGS_QUERYResult,
  USER_UPCOMING_BOOKINGS_QUERYResult,
  USER_PROFILE_BY_CLERK_ID_QUERYResult,
  USER_PROFILE_WITH_PREFERENCES_QUERYResult,
  SESSION_FOR_BOOKING_QUERYResult,
  EXISTING_BOOKING_QUERYResult,
  BOOKING_FOR_CANCEL_QUERYResult,
  BOOKING_FOR_ATTENDANCE_QUERYResult,
  MONTHLY_BOOKINGS_COUNT_QUERYResult,
};


export declare const internalGroqTypeReferenceTo: unique symbol;

declare global {
  interface SanityQueries {
    "*[_type == \"activity\"] | order(name asc)": unknown;
    "*[_type == \"venue\"] | order(name asc)": unknown;
    "*[_type == \"category\"] | order(name asc)": unknown;
  }
}
